In [6]:
# tensor initialization
import torch

# empty tensor init
# generate a empty tensor, like ndarray of NumPy
# 5 * 3 indicate 5 rows 3 columns
x = torch.Tensor(5, 3)
print(x)

# random tensor init
x = torch.rand(5, 3)
print(x)

tensor([[2.6752e-01, 9.5131e-02, 7.8223e-01],
        [8.1581e-01, 0.0000e+00, 3.6893e+19],
        [1.7635e-26, 2.5244e-29, 4.7852e-01],
        [2.7295e-02, 3.2061e-01, 9.7171e-01],
        [9.6954e-01, 9.4421e-01, 3.0234e-01]])
tensor([[0.5775, 0.3317, 0.5955],
        [0.5984, 0.3966, 0.0977],
        [0.9233, 0.0286, 0.0194],
        [0.6715, 0.2765, 0.9282],
        [0.1152, 0.3821, 0.3197]])


In [14]:
# tensor adding
import torch

a = torch.Tensor([[2, 1, -1], [1, -2, 3], [-2, 1, 2]])
b = torch.Tensor([[1, -1, 2], [-2, 1, 3], [2, -2, 1]])
print(a)
print(b)

result = a + b
result = torch.square(result)
print(result)

a2 = torch.square(a)
b2 = torch.square(b)
ab = a * b
ba = b * a
result2 = a2 + ab + ba + b2
print(result2)

print(result == result2)

tensor([[ 2.,  1., -1.],
        [ 1., -2.,  3.],
        [-2.,  1.,  2.]])
tensor([[ 1., -1.,  2.],
        [-2.,  1.,  3.],
        [ 2., -2.,  1.]])
tensor([[ 9.,  0.,  1.],
        [ 1.,  1., 36.],
        [ 0.,  1.,  9.]])
tensor([[ 9.,  0.,  1.],
        [ 1.,  1., 36.],
        [ 0.,  1.,  9.]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [52]:
# tensor product
import torch

a = torch.Tensor([[1.1, 1.2, 1.3], [1.4, 1.5, 1.6]])
b = torch.Tensor([[2.1, 2.2], [2.3, 2.4], [2.5, 2.6]])

print(torch.matmul(a, b))

x = torch.Tensor([[6, 12, -6], [-12, 12, -4], [0, -12, 8]])
# x = torch.Tensor([[4, 7], [2, 6]])
xinv = torch.linalg.inv(x)
print(torch.matmul(x, xinv))

tensor([[ 8.3200,  8.6800],
        [10.3900, 10.8400]])
tensor([[1.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 0.0000],
        [0.0000, 0.0000, 1.0000]])
