In [6]:
# tensor initialization
import torch

# empty tensor init
# generate a empty tensor, like ndarray of NumPy
# 5 * 3 indicate 5 rows 3 columns
x = torch.Tensor(5, 3)
print(x)

# random tensor init
x = torch.rand(5, 3)
print(x)

tensor([[2.6752e-01, 9.5131e-02, 7.8223e-01],
        [8.1581e-01, 0.0000e+00, 3.6893e+19],
        [1.7635e-26, 2.5244e-29, 4.7852e-01],
        [2.7295e-02, 3.2061e-01, 9.7171e-01],
        [9.6954e-01, 9.4421e-01, 3.0234e-01]])
tensor([[0.5775, 0.3317, 0.5955],
        [0.5984, 0.3966, 0.0977],
        [0.9233, 0.0286, 0.0194],
        [0.6715, 0.2765, 0.9282],
        [0.1152, 0.3821, 0.3197]])


In [14]:
# tensor adding
import torch

a = torch.Tensor([[2, 1, -1], [1, -2, 3], [-2, 1, 2]])
b = torch.Tensor([[1, -1, 2], [-2, 1, 3], [2, -2, 1]])
print(a)
print(b)

result = a + b
result = torch.square(result)
print(result)

a2 = torch.square(a)
b2 = torch.square(b)
ab = a * b
ba = b * a
result2 = a2 + ab + ba + b2
print(result2)

print(result == result2)

tensor([[ 2.,  1., -1.],
        [ 1., -2.,  3.],
        [-2.,  1.,  2.]])
tensor([[ 1., -1.,  2.],
        [-2.,  1.,  3.],
        [ 2., -2.,  1.]])
tensor([[ 9.,  0.,  1.],
        [ 1.,  1., 36.],
        [ 0.,  1.,  9.]])
tensor([[ 9.,  0.,  1.],
        [ 1.,  1., 36.],
        [ 0.,  1.,  9.]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [52]:
# tensor product
import torch

a = torch.Tensor([[1.1, 1.2, 1.3], [1.4, 1.5, 1.6]])
b = torch.Tensor([[2.1, 2.2], [2.3, 2.4], [2.5, 2.6]])

print(torch.matmul(a, b))

x = torch.Tensor([[6, 12, -6], [-12, 12, -4], [0, -12, 8]])
# x = torch.Tensor([[4, 7], [2, 6]])
xinv = torch.linalg.inv(x)
print(torch.matmul(x, xinv))

tensor([[ 8.3200,  8.6800],
        [10.3900, 10.8400]])
tensor([[1.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 0.0000],
        [0.0000, 0.0000, 1.0000]])


In [5]:
import torch

a = torch.randn(4, 3, 3)
print(a)
print(a.unsqueeze(0))

labels = torch.cat([torch.ones(4), torch.zeros(5)], dim=0).long()
print(labels)

tensor([[[-1.0552, -0.3082, -1.5270],
         [-0.1937,  0.3067, -2.2731],
         [-0.9198, -1.8613, -0.0089]],

        [[-0.1057, -2.6443,  1.1553],
         [ 1.2394, -0.7063,  2.0697],
         [-0.5609, -0.5982, -0.6893]],

        [[ 0.4327,  0.6643, -0.0927],
         [-0.1069, -0.6832, -1.1978],
         [-0.1144,  0.0680,  0.9189]],

        [[-0.5502, -0.3344, -1.4720],
         [ 0.4613,  1.1215,  0.1458],
         [ 1.4775, -0.1735, -0.8749]]])
tensor([[[[-1.0552, -0.3082, -1.5270],
          [-0.1937,  0.3067, -2.2731],
          [-0.9198, -1.8613, -0.0089]],

         [[-0.1057, -2.6443,  1.1553],
          [ 1.2394, -0.7063,  2.0697],
          [-0.5609, -0.5982, -0.6893]],

         [[ 0.4327,  0.6643, -0.0927],
          [-0.1069, -0.6832, -1.1978],
          [-0.1144,  0.0680,  0.9189]],

         [[-0.5502, -0.3344, -1.4720],
          [ 0.4613,  1.1215,  0.1458],
          [ 1.4775, -0.1735, -0.8749]]]])
tensor([1, 1, 1, 1, 0, 0, 0, 0, 0])


In [25]:
import torch
import torch.nn.functional as F

# Example of target with class indices
input = torch.randn(3, 5, requires_grad=True)
print(input)
# target = torch.empty(3, dtype=torch.long).random_(5)
target = torch.cat([torch.ones(2), torch.zeros(3)], dim=0).float()
target = target.repeat(3, 1)
print(target)
output = F.cross_entropy(input, target)
output.backward()

tensor([[ 1.1312, -0.2894, -1.7286, -0.3512,  0.3030],
        [ 2.2057,  0.4267, -1.2856,  1.8601, -1.2192],
        [ 1.4765,  1.4323,  0.1407,  0.3044, -0.2838]], requires_grad=True)
tensor([[1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.]])


In [45]:
import torch

a = torch.randn(4, 3, requires_grad=True)
b = a.unsqueeze(1)
print(a.shape)
print(b.shape)
c = b.repeat(1, 3, 1)
print(c.shape)
d = c.reshape(c.size(0) * c.size(1), c.size(2))
print(d.shape)

torch.Size([4, 3])
torch.Size([4, 1, 3])
torch.Size([4, 3, 3])
torch.Size([12, 3])


In [44]:
import torch

a = torch.randn(4)
print(a)
b = a.unsqueeze(-1)
print(b)
c = b.repeat(1, 3)
print(c)
d = c.reshape(12)
print(d)

tensor([ 0.5798, -0.1765, -0.4573,  2.0085])
tensor([[ 0.5798],
        [-0.1765],
        [-0.4573],
        [ 2.0085]])
tensor([[ 0.5798,  0.5798,  0.5798],
        [-0.1765, -0.1765, -0.1765],
        [-0.4573, -0.4573, -0.4573],
        [ 2.0085,  2.0085,  2.0085]])
tensor([ 0.5798,  0.5798,  0.5798, -0.1765, -0.1765, -0.1765, -0.4573, -0.4573,
        -0.4573,  2.0085,  2.0085,  2.0085])


In [48]:
import torch

a = torch.randn(5, 1, requires_grad=True)
print(torch.topk(a, 1, dim=1))

torch.return_types.topk(
values=tensor([[-1.3251],
        [-0.6610],
        [ 0.3701],
        [ 1.3044],
        [ 0.2862]], grad_fn=<TopkBackward0>),
indices=tensor([[0],
        [0],
        [0],
        [0],
        [0]]))


In [ ]:

a = 88.06
ax = [89.72, 92.58]